Improve security by refusing to run workflow if brunch secrets are not set.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,8 +10,18 @@ concurrency:
   group: environment-${{ github.ref }}
   cancel-in-progress: true
 jobs:
+  check-secrets:
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Check for BRUNCH_PRIV and BRUNCH_PEM secrets
+        run: |
+          if [ -z "${{ secrets.BRUNCH_PRIV }}" ] || [ -z "${{ secrets.BRUNCH_PEM }}" ]; then
+            echo "Error: BRUNCH_PRIV and/or BRUNCH_PEM secrets are not set."
+            exit 1
+          fi
   prepare-kernels:
     name: Prepare Kernels
+    needs: check-secrets
     runs-on: ubuntu-24.04
     outputs:
       matrix: ${{ steps.kernels.outputs.matrix }}
@@ -100,7 +110,7 @@ jobs:
         run: |
           yes | DEBIAN_FRONTEND=noninteractive sudo apt update
           #yes | DEBIAN_FRONTEND=noninteractive sudo apt dist-upgrade
-          yes | DEBIAN_FRONTEND=noninteractive sudo apt install gcc-12 g++-12 git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison sbsigntool python3-protobuf rdfind zstd
+          yes | DEBIAN_FRONTEND=noninteractive sudo apt install gcc-12 g++-12 git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison sbsigntool python3-protobuf rdfind z[...]
           sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 110 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
           pip3 install --upgrade google-api-python-client
       - name: Free some disk space
